# Generated by Django 5.0.2 on 2024-02-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=30)),
                ('ano', models.IntegerField()),
                ('nafta', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
